# Generated by Django 5.0 on 2023-12-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('date_report', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('cable', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=255)),
                ('report', models.CharField(max_length=20000)),
                ('other_job', models.CharField(max_length=20000)),
                ('exist', models.CharField(max_length=20000)),
                ('propose', models.CharField(max_length=20000)),
                ('date', models.CharField(max_length=255)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
