# Generated by Django 5.0 on 2023-12-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_delete_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='creator',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
