# Generated by Django 5.0 on 2024-01-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sv_cable',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='sv_device',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='sv_power',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
