# Generated by Django 5.0 on 2024-01-01 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_report_sv_cable_report_sv_device_report_sv_power'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Report2',
        ),
    ]
