# Generated by Django 5.0 on 2024-01-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_rename_report_report2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reported',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('date_report', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('cable', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=255)),
                ('report', models.CharField(max_length=20000)),
                ('other_job', models.CharField(max_length=20000)),
                ('exist', models.CharField(max_length=20000)),
                ('propose', models.CharField(max_length=20000)),
                ('creator', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('sv_device', models.CharField(max_length=255)),
                ('sv_cable', models.CharField(max_length=255)),
                ('sv_power', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Report2',
        ),
    ]
