# Generated by Django 5.0 on 2023-12-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='note',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
